# Generated by Django 4.0.6 on 2022-07-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('logid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(default='', max_length=30)),
                ('name', models.TextField(max_length=20)),
                ('email', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=20)),
            ],
        ),
    ]
